export default {
    "premium_post": [
        {
            "id": 1,
            "category_id": 1,
            "content_en": "<p>vcb cb</p>",
            "content_bn": `জ্যামাইকা, জ্যাকসন হাইটস, উডসাইড যে কোন এরিয়ায় ২০১৭/২০১৮ সালের র‌্যাভ-৪ গাড়ির জন্য ড্রাইভার আবশ্যক। </div> <div class="text-center fw-bold driver">929-229-6836</div>`,
            "is_premium": "Yes",
            "category": {
                "id": 1,
                "name_en": "Constance Ryan",
                "name_bn": "ড্রাইভার আবশ্যক",
            },
        },
        {
            "id": 2,
            "category_id": 1,
            "content_en": "<p>vcb cb</p>",
            "content_bn": `জ্যামাইকা, জ্যাকসন হাইটস, উডসাইড যে কোন এরিয়ায় ২০১৭/২০১৮ সালের র‌্যাভ-৪ গাড়ির জন্য ড্রাইভার আবশ্যক। </div> <div class="text-center fw-bold driver">929-229-6836</div>`,
            "is_premium": "Yes",
            "category": {
                "id": 1,
                "name_en": "Constance Ryan",
                "name_bn": "ড্রাইভার আবশ্যক",
            },
        },
        {
            "id": 3,
            "category_id": 1,
            "content_en": "<p>vcb cb</p>",
            "content_bn": `জ্যামাইকা, জ্যাকসন হাইটস, উডসাইড যে কোন এরিয়ায় ২০১৭/২০১৮ সালের র‌্যাভ-৪ গাড়ির জন্য ড্রাইভার আবশ্যক। </div> <div class="text-center fw-bold driver">929-229-6836</div>`,
            "is_premium": "Yes",
            "category": {
                "id": 1,
                "name_en": "Constance Ryan",
                "name_bn": "ড্রাইভার আবশ্যক",
            },
        },
        {
            "id": 4,
            "category_id": 1,
            "content_en": "<p>vcb cb</p>",
            "content_bn": `জ্যামাইকা, জ্যাকসন হাইটস, উডসাইড যে কোন এরিয়ায় ২০১৭/২০১৮ সালের র‌্যাভ-৪ গাড়ির জন্য ড্রাইভার আবশ্যক। </div> <div class="text-center fw-bold driver">929-229-6836</div>`,
            "is_premium": "Yes",
            "category": {
                "id": 1,
                "name_en": "Constance Ryan",
                "name_bn": "ড্রাইভার আবশ্যক",
            },
        },
        {
            "id": 5,
            "category_id": 1,
            "content_en": "<p>vcb cb</p>",
            "content_bn": `জ্যামাইকা, জ্যাকসন হাইটস, উডসাইড যে কোন এরিয়ায় ২০১৭/২০১৮ সালের র‌্যাভ-৪ গাড়ির জন্য ড্রাইভার আবশ্যক। </div> <div class="text-center fw-bold driver">929-229-6836</div>`,
            "is_premium": "Yes",
            "category": {
                "id": 1,
                "name_en": "Constance Ryan",
                "name_bn": "ড্রাইভার আবশ্যক",
            },
        },
    ],
    "category_post": [
        {
            "id": 1,
            "slug_en": "constance-ryan",
            "slug_bn": "arthur-little",
            "name_en": "Constance Ryan",
            "name_bn": "রুম ভাড়া",
            "posts": [
                {
                    "id": 1,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `বাফেলোতে নেয়ার বাস এন্ড ডাউন টাউনের কাছে একটি চার বেডরুমের বাড়ীর ভাড়া দেওয়া হবে। যোগযোগঃ <span class="fw-bold">646-240-3517</span>. টিসি-০৩৩৯/৪`,
                    "is_premium": "No",
                },
                {
                    "id": 2,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `বাফেলোতে নেয়ার বাস এন্ড ডাউন টাউনের কাছে একটি চার বেডরুমের বাড়ীর ভাড়া দেওয়া হবে। যোগযোগঃ <span class="fw-bold">646-240-3517</span>. টিসি-০৩৩৯/৪`,
                    "is_premium": "No",
                },
                {
                    "id": 3,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `বাফেলোতে নেয়ার বাস এন্ড ডাউন টাউনের কাছে একটি চার বেডরুমের বাড়ীর ভাড়া দেওয়া হবে। যোগযোগঃ <span class="fw-bold">646-240-3517</span>. টিসি-০৩৩৯/৪`,
                    "is_premium": "No",
                },
                {
                    "id": 4,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `বাফেলোতে নেয়ার বাস এন্ড ডাউন টাউনের কাছে একটি চার বেডরুমের বাড়ীর ভাড়া দেওয়া হবে। যোগযোগঃ <span class="fw-bold">646-240-3517</span>. টিসি-০৩৩৯/৪`,
                    "is_premium": "No",
                },
                {
                    "id": 5,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `বাফেলোতে নেয়ার বাস এন্ড ডাউন টাউনের কাছে একটি চার বেডরুমের বাড়ীর ভাড়া দেওয়া হবে। যোগযোগঃ <span class="fw-bold">646-240-3517</span>. টিসি-০৩৩৯/৪`,
                    "is_premium": "No",
                },
            ],
        },
        {
            "id": 2,
            "slug_en": "constance-ryan",
            "slug_bn": "arthur-little",
            "name_en": "Constance Ryan",
            "name_bn": "পাত্র পাত্রী",
            "posts": [
                {
                    "id": 1,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 2,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 3,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 4,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 5,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
            ],
        },
        {
            "id": 3,
            "slug_en": "constance-ryan",
            "slug_bn": "arthur-little",
            "name_en": "Constance Ryan",
            "name_bn": "পাত্র পাত্রী",
            "posts": [
                {
                    "id": 1,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 2,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 3,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 4,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 5,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
            ],
        },
        {
            "id": 4,
            "slug_en": "constance-ryan",
            "slug_bn": "arthur-little",
            "name_en": "Constance Ryan",
            "name_bn": "পাত্র পাত্রী",
            "posts": [
                {
                    "id": 1,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 2,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 3,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 4,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 5,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
            ],
        },
        {
            "id": 5,
            "slug_en": "constance-ryan",
            "slug_bn": "arthur-little",
            "name_en": "Constance Ryan",
            "name_bn": "পাত্র পাত্রী",
            "posts": [
                {
                    "id": 1,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 2,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 3,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 4,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
                {
                    "id": 5,
                    "category_id": 1,
                    "content_en": "<p>vcb cb</p>",
                    "content_bn": `পাত্র/পাত্রী চাই পাত্র-পাত্রী কানেকশন। সম্ভ্রান্ত, ভদ্র, মার্জিত ও শিক্ষিত পাত্র-পাত্রীর সন্ধান পেতে যোগাযোগ করুন। For educated, highly educated grown up boys & girls. Call: <span class="fw-bold">917-312-9170.</span> Tc-1218/8`,
                    "is_premium": "No",
                },
            ],
        },
    ],
};
